### ISSUE TITLE
How to convert MAC address?

### ISSUE THREAD

**Issue by maxholgasson** [koen-github/WakeOnLan-ESP8266#1]
Hi, my board is connected to wifi and sneding WOL packets but my NAS does not wake up with that ESP
Is my mac correctly converted?

00:21:32:4C:9A:03

byte mac[] = { 0x00, 0x21, 0x32, 0x4C, 0x9A, 0x03 };

When sending packets from a PC then the NAS will wake up

**Comment by koenieee** [comment]
Hi Max,

Nice to hear my library is being used, although it doesn't work :(
Your mac address is correctly converted, are you sure it's also correct?
Can you make sure you are connected to the same wifi network your NAS is attached to?

I tested it when I committed to the master branch, and it was working perfectly! Although I did not tested it with a NAS, but with a normal windows 10 PC.

Kind regards,

Koen

**Comment by maxholgasson** [comment]
Hi,

so it took some time to get to the esp again..

Yes it is correct and the ip as well. I'm using a program on the laptop 
(connected over wifi) and there it works. Also with another pc connected 
over cable to the router.

Do you have any idea how to check what's wrong?

Thats the serial output:
Connecting to WiFi
Connecting........
Connected to Router1
IP address: 192.168.1.33
Sending WOL Packet...
Sending WOL Packet...
Sending WOL Packet...
Sending WOL Packet...

Am 23.05.16 um 20:42 schrieb Koen van der Kruk:

**Comment by maxholgasson** [comment]
Hi, I managed to to analyse it with wireshark and that's the result.  Do you know where I could search for the failure?

![wireshark](https://cloud.githubusercontent.com/assets/4289347/19854499/91e4f452-9f6f-11e6-9b31-e8448fdd0067.png)

**Comment by koenieee** [comment]
Is this the wireshark logging of the ESP? Or just a log of your PC?
Maybe you can compare these two, and see what's going wrong.

What kind of ESP do you have btw?

**Comment by maxholgasson** [comment]
I have an ESP8266MOD on a WeMos D1 board.  My router recorded that log in wireshark format and I opened the file with wireshark.
Is that what you mean?

**Comment by koenieee** [comment]
Yes that's what I meant. But when you send a WOL package from a PC, can you compare that one with the ESP 8266?

**Comment by maxholgasson** [comment]
ah ok, good idea!
I captured the WOL signal send when clicked the button on the router webinterface. That also works for sure and wake up the NAS
![esp8266](https://cloud.githubusercontent.com/assets/4289347/19854953/21133286-9f72-11e6-8680-2a0b4553388f.png)
![workingwol](https://cloud.githubusercontent.com/assets/4289347/19854954/2117a244-9f72-11e6-94b3-b2efdfd727c4.png)

**Comment by koenieee** [comment]
Can you specify what the ESP is and what the ROUTER is, thank you 👍

**Comment by maxholgasson** [comment]
The first is the ESP, the second the router. I'm capturing the PC also now

**Comment by koenieee** [comment]
Can you put in here in plain text? Including the full frame

**Comment by maxholgasson** [comment]
you mean the wireshark eth-file?

Maybe that helps as well. It's a summary from wireshark

```
ESP:

"49","7.251539","192.168.1.22","192.168.1.23","WOL","144","MagicPacket for Synology_4c:9a:01 (00:11:32:4c:9a:01)"

Router:
"113","9.067665","AvmAudio_62:ae:c1","Broadcast","WOL","116","MagicPacket for Synology_4c:9a:01 (00:11:32:4c:9a:01)"



```

**Comment by koenieee** [comment]
The full request package. You can also send the eth file in a private message

**Comment by kebibg** [comment]
Hi mate,
MAC of Synology_4c:9a:01 is 00:11:32:4c:9a:01 but you configure 00:21:32:4C:9A:03. They are total different.
try to configure correct MAC in arduino sketch.

Regards

**Comment by koenieee** [comment]
You have to set your own mac address

**Comment by orimate** [comment]
Hi, is the problem solved? NAS and ESP are in the same network, MAC is set in sketch, but NAS don t wakes up. If I send a mesage from Node Red I see that with wireshark but from esp8266 comes nothing.

**Comment by orimate** [comment]
I compiled with arduinio, I need to use Arduinio IDE?

**Comment by orimate** [comment]
I compiled today with atom and platform io, now it works. Sorry my fault.
