### ISSUE TITLE
Case sensitive error

### ISSUE THREAD

**Issue by sbaloo** [koen-github/WakeOnLan-ESP8266#7]
in WakeOnLan.h

its not #include <WiFiUDP.h> but #include <WiFiUdp.h> to work on unix compilation

**Comment by marcelmiguel** [comment]
I agree, there is an error, must be "WiFiUdp.h".

My environment:
- Ubuntu 
- VSCode 1.45
- ESP8266 2.7.1.

**Comment by koenieee** [comment]
merged pull request, closed issue
